// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package tutorial.proto.code;

public interface UserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
