// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package tutorial.proto.code;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ID = 1;</code>
   * @return The iD.
   */
  int getID();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
